### ISSUE TITLE
1.1.0版本没问题 升级 1.2.0 直接挂了

### ISSUE THREAD

**Issue by Xxj-star** [FlyJingFish/GradientTextView#1]
![image](https://github.com/FlyJingFish/GradientTextView/assets/41047773/77e1ed1d-e043-4144-92a6-fdd1f4429804)
![image](https://github.com/FlyJingFish/GradientTextView/assets/41047773/b76166fd-a6ba-406a-b7b8-a46beac83380)
![G)C@2`{N }P9V$P Z$KCZG3](https://github.com/FlyJingFish/GradientTextView/assets/41047773/fd75f7e3-d450-487c-a1a5-6e6f6a993a27)

**Comment by FlyJingFish** [comment]
升级版本最新版本 1.2.2 已经解决此问题
