### ISSUE TITLE
看起来不错，可否支持多种以上颜色变色文字超长Marqueen效果？

### ISSUE THREAD

**Issue by Liberations** [FlyJingFish/GradientTextView#2]
看属性介绍只支持开始中间结束颜色

**Comment by FlyJingFish** [comment]
xml中设置按照shape的渐变色设置只定义了3个颜色，代码中没有限制。
另外你说的Marqueen效果有很多种实现方式，其中有一种您知道的话也就不会问我支不支持多种颜色这种问题了
